#!/bin/bash
# freebuff-sandbox: runs Freebuff using the locally built image

PROJECT_DIR="$(pwd)"
FREEBUFF_HOME_DIR="$HOME/.freebuff-home"

mkdir -p "$FREEBUFF_HOME_DIR"

exec podman run --rm -it \
  --userns=keep-id \
  -v "$PROJECT_DIR:/workspace:rw,Z" \
  -v "$FREEBUFF_HOME_DIR:/root:rw,Z" \
  -w /workspace \
  localhost/freebuff-image:latest \
  freebuff "$@"
